stacks:
  - name: VPCProd
    template: vpc.json
    parameters: []

  - name: PublicSubnetsProd
    template: public-subnets.json
    parameters:
    - param_name: InternetGateway
      value:
        stack: VPCProd
        output: InternetGateway
    - param_name: VpcId
      value:
        stack: VPCProd
        output: VpcId
